export const facultyDetails = [
    {
        name: "Dr. John Smith",
        position: "Professor",
        department: "Computer Science",
        researchInterests: ["Artificial Intelligence", "Machine Learning"],
        email: "john.smith@example.com",
        office: "Room 101",
        phoneNumber: "+1 (123) 456-7890",
        address: "123 Main St, City, Country",
        imageUrl: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 15,
        about: "Dr. John Smith is a Professor in the Computer Science department. His research interests include Artificial Intelligence and Machine Learning. With 15 years of experience, he has made significant contributions to the field."
    },
    {
        name: "Dr. Emily Johnson",
        position: "Associate Professor",
        department: "Electrical Engineering",
        researchInterests: ["Renewable Energy", "Power Systems"],
        email: "emily.johnson@example.com",
        office: "Room 202",
        phoneNumber: "+1 (234) 567-8901",
        address: "456 Elm St, City, Country",
        imageUrl: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 12,
        about: "Dr. Emily Johnson is an Associate Professor in the Electrical Engineering department. Her research focuses on Renewable Energy and Power Systems. With 12 years of experience, she has published numerous papers in her field."
    },
    {
        name: "Prof. David Brown",
        position: "Assistant Professor",
        department: "Mechanical Engineering",
        researchInterests: ["Fluid Mechanics", "Thermodynamics"],
        email: "david.brown@example.com",
        office: "Room 303",
        phoneNumber: "+1 (345) 678-9012",
        address: "789 Oak St, City, Country",
        imageUrl: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 8,
        about: "Prof. David Brown is an Assistant Professor in the Mechanical Engineering department. His research interests include Fluid Mechanics and Thermodynamics. He has 8 years of experience and has been actively involved in several research projects."
    },
    {
        name: "Dr. Sarah Wilson",
        position: "Professor",
        department: "Chemistry",
        researchInterests: ["Organic Chemistry", "Materials Science"],
        email: "sarah.wilson@example.com",
        office: "Room 404",
        phoneNumber: "+1 (456) 789-0123",
        address: "101 Pine St, City, Country",
        imageUrl: "https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 20,
        about: "Dr. Sarah Wilson is a Professor in the Chemistry department. Her research focuses on Organic Chemistry and Materials Science. With 20 years of experience, she has received several awards for her outstanding contributions to the field."
    },
    {
        name: "Prof. Michael Davis",
        position: "Associate Professor",
        department: "Physics",
        researchInterests: ["Quantum Mechanics", "Particle Physics"],
        email: "michael.davis@example.com",
        office: "Room 505",
        phoneNumber: "+1 (567) 890-1234",
        address: "202 Cedar St, City, Country",
        imageUrl: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 14,
        about: "Prof. Michael Davis is an Associate Professor in the Physics department. His research interests include Quantum Mechanics and Particle Physics. With 14 years of experience, he has published extensively in top-tier journals."
    },
    {
        name: "Dr. Lisa Martinez",
        position: "Assistant Professor",
        department: "Biology",
        researchInterests: ["Genetics", "Evolutionary Biology"],
        email: "lisa.martinez@example.com",
        office: "Room 606",
        phoneNumber: "+1 (678) 901-2345",
        address: "303 Maple St, City, Country",
        imageUrl: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 9,
        about: "Dr. Lisa Martinez is an Assistant Professor in the Biology department. Her research focuses on Genetics and Evolutionary Biology. With 9 years of experience, she is passionate about understanding the mechanisms of evolution."
    },
    {
        name: "Prof. James Anderson",
        position: "Professor",
        department: "Mathematics",
        researchInterests: ["Number Theory", "Algebra"],
        email: "james.anderson@example.com",
        office: "Room 707",
        phoneNumber: "+1 (789) 012-3456",
        address: "404 Walnut St, City, Country",
        imageUrl: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 18,
        about: "Prof. James Anderson is a Professor in the Mathematics department. His research interests include Number Theory and Algebra. With 18 years of experience, he has mentored numerous students and researchers in his field."
    },
    {
        name: "Dr. John Smith",
        position: "Professor",
        department: "Computer Science",
        researchInterests: ["Artificial Intelligence", "Machine Learning"],
        email: "john.smith@example.com",
        office: "Room 101",
        phoneNumber: "+1 (123) 456-7890",
        address: "123 Main St, City, Country",
        imageUrl: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 15,
        about: "Dr. John Smith is a Professor in the Computer Science department. His research interests include Artificial Intelligence and Machine Learning. With 15 years of experience, he has made significant contributions to the field."
    },
    {
        name: "Dr. Emily Johnson",
        position: "Associate Professor",
        department: "Electrical Engineering",
        researchInterests: ["Renewable Energy", "Power Systems"],
        email: "emily.johnson@example.com",
        office: "Room 202",
        phoneNumber: "+1 (234) 567-8901",
        address: "456 Elm St, City, Country",
        imageUrl: "https://images.pexels.com/photos/1212984/pexels-photo-1212984.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 12,
        about: "Dr. Emily Johnson is an Associate Professor in the Electrical Engineering department. Her research focuses on Renewable Energy and Power Systems. With 12 years of experience, she has published numerous papers in her field."
    },
    {
        name: "Prof. Brian Smith",
        position: "Professor",
        department: "Philosophy",
        researchInterests: ["Ethics", "Political Philosophy"],
        email: "brian.smith@example.com",
        office: "Room 111",
        phoneNumber: "+1 (234) 567-8901",
        address: "789 Elm St, City, Country",
        imageUrl: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=600",
        yearsOfExperience: 22,
        about: "Prof. Brian Smith is a Professor in the Philosophy department. His research interests include Ethics and Political Philosophy. With 22 years of experience, he has authored several influential books and articles in his field."
    },
]
